import assert from "node:assert/strict"
import { readdir, readFile } from "node:fs/promises"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "..")
const sourceRoot = path.join(root, "src")
const workflowRoot = path.join(root, ".github", "workflows")

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    const target = path.join(directory, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(target)))
    else if (/\.(?:ts|tsx)$/.test(entry.name)) files.push(target)
  }

  return files
}

const forbiddenPatterns = [
  ["eval", /\beval\s*\(/],
  ["Function constructor", /\bnew\s+Function\s*\(/],
  ["dangerouslySetInnerHTML", /dangerouslySetInnerHTML/],
  ["javascript URL", /["'`]javascript:/i],
  ["document.write", /document\.write\s*\(/],
]

const violations = []
for (const file of await walk(sourceRoot)) {
  const source = await readFile(file, "utf8")
  const relativePath = path.relative(root, file)
  const hasVettedChartStyleInjection =
    relativePath === "src/components/ui/chart.tsx" &&
    (source.match(/dangerouslySetInnerHTML/g) ?? []).length === 1 &&
    source.includes("const ChartStyle") &&
    source.includes("<style") &&
    source.includes("--color-${key}")

  for (const [label, pattern] of forbiddenPatterns) {
    if (
      pattern.test(source) &&
      !(label === "dangerouslySetInnerHTML" && hasVettedChartStyleInjection)
    ) {
      violations.push(`${relativePath}: ${label}`)
    }
  }
}

const workflowFiles = (await readdir(workflowRoot)).filter((file) =>
  /\.ya?ml$/.test(file)
)

// Composite action definitions under `.github/actions/**` run `uses:` steps of
// their own. Reading only `.github/workflows` left those steps invisible, so an
// unpinned reference there would pass the audit. This repository defines none
// today, which is exactly why the gap is worth closing now: it cannot be
// noticed by inspection until someone adds the first one.
const localActionRoot = path.join(root, ".github", "actions")
async function collectLocalActionFiles(directory) {
  let entries
  try {
    entries = await readdir(directory, { withFileTypes: true })
  } catch (error) {
    if (error.code === "ENOENT") return []
    throw error
  }

  const files = []
  for (const entry of entries) {
    const target = path.join(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await collectLocalActionFiles(target)))
    } else if (entry.name === "action.yml" || entry.name === "action.yaml") {
      files.push(target)
    }
  }
  return files
}
const localActionFiles = await collectLocalActionFiles(localActionRoot)

// Resolved SHA -> tag mapping, regenerated by `scripts/sync-action-pins.mjs`.
// Read once here so the action audit below stays hermetic and offline.
const actionPins = JSON.parse(
  await readFile(path.join(root, "etc", "action-pins.json"), "utf8")
)
assert.ok(
  workflowFiles.length > 0,
  "Expected at least one GitHub Actions workflow"
)

// Lowest action major this repository is willing to run. A SHA pin alone only
// guarantees immutability, not that the pinned major is still the supported one,
// so a stale pin such as `actions/checkout@<sha> # v4` stays valid forever
// without this floor.
//
// This table is an ALLOWLIST, not a floor-with-default. A `uses:` reference to
// an action that is absent fails the audit, so adding a workflow dependency
// cannot silently skip the version check.
const actionMajorFloors = new Map([
  ["actions/checkout", 7],
  ["actions/setup-node", 7],
  ["actions/upload-artifact", 7],
  ["actions/cache", 6],
  ["peter-evans/create-pull-request", 8],
  ["actions/dependency-review-action", 5],
  ["github/codeql-action/analyze", 4],
  ["github/codeql-action/init", 4],
  ["zizmorcore/zizmor-action", 0],
])

// Workflows and local composite actions are audited by the same rules; only the
// label used in failure messages differs.
const actionSourcePaths = [
  ...workflowFiles.map((file) => ({
    label: file,
    absolute: path.join(workflowRoot, file),
  })),
  ...localActionFiles.map((file) => ({
    label: path.relative(root, file),
    absolute: file,
  })),
]

for (const { label: file, absolute } of actionSourcePaths) {
  const workflow = await readFile(absolute, "utf8")
  // Parsed line by line rather than by one combined `uses: <name> @<ref>
  // # <major>` regex. Such a regex has to guess where the action name ends and
  // the ref begins, and every guess is a way for a SHA to be absorbed into the
  // wrong capture group and stop being checked at all. Splitting on the real
  // separators keeps each field exact.
  //
  // `uses:` is matched at any indentation, not only as a step's first key: the
  // common `- name: ...` followed by `uses:` form is used in this repository
  // (sync-upstream.yml), and anchoring on `- uses:` hid exactly those steps from
  // every check below. Anchoring to the start of a line also means a comment
  // that merely mentions the `uses:` key cannot trip these assertions.
  // The version comment stays optional so `docker://` images and unpinned
  // references still reach the assertions instead of being skipped.
  // The YAML flow form (`- uses: { name: x }`) is intentionally not recognised.
  // Rejecting it is fail-closed and no workflow in this repository uses it.
  const usesPattern = /^[ \t]*(?:-[ \t]+)?uses:[ \t]+(?<rest>\S.*?)[ \t]*$/
  // Unanchored: this runs against the remainder after `uses:`, which begins at the
  // action name, so a leading `^` would never line up with the `#`.
  const commentPattern = /#[ \t]*v?[ \t]*(?<major>\d+)/
  const actionReferences = []

  for (const line of workflow.split("\n")) {
    const match = usesPattern.exec(line)
    if (!match) continue

    const rest = match.groups.rest
    // Cut a trailing comment off first so it can never bleed into the ref.
    const withoutComment = rest.replace(/[ \t]+#.*$/, "").trimEnd()
    const declaredMajorText = commentPattern.exec(rest)?.groups?.major
    const separator = withoutComment.indexOf("@")

    actionReferences.push({
      action: (separator === -1
        ? withoutComment
        : withoutComment.slice(0, separator)
      ).trim(),
      reference:
        separator === -1 ? undefined : withoutComment.slice(separator + 1),
      declaredMajorText,
    })
  }

  for (const { action, reference, declaredMajorText } of actionReferences) {
    if (action.startsWith("./") || action.startsWith("../")) continue

    assert.match(
      reference ?? "",
      /^[0-9a-f]{40}$/,
      `${file}: ${action} must be pinned to an immutable full commit SHA`
    )

    // The trailing comment is human-editable text, so it cannot be the source
    // of truth. `etc/action-pins.json` is the resolved truth: every SHA in it was
    // matched against the tags that actually point at it via
    // `scripts/sync-action-pins.mjs`. Checking the comment against that file is
    // what makes the floor meaningful — otherwise `actions/checkout@<v4 sha>
    // # v7.0.0` passes every comment-only assertion.
    // `reference` already has the `@` separator removed by the line parser above.
    const sha = reference
    const pin = actionPins[action]
    assert.notEqual(
      pin,
      undefined,
      `${file}: ${action} is not listed in etc/action-pins.json; run \`node scripts/sync-action-pins.mjs\``
    )
    assert.equal(
      pin.sha,
      sha,
      `${file}: ${action} is pinned to ${sha} but etc/action-pins.json records ${pin.sha}. Re-run \`node scripts/sync-action-pins.mjs\`.`
    )

    const floor = actionMajorFloors.get(action)
    assert.notEqual(
      floor,
      undefined,
      `${file}: ${action} is not listed in actionMajorFloors; add it with its minimum supported major`
    )

    const resolvedMajor = Number(pin.version.split(".")[0])
    assert.ok(
      resolvedMajor >= floor,
      `${file}: ${action} resolves to v${pin.version} but this repository requires v${floor} or newer`
    )
    assert.ok(
      declaredMajorText !== undefined,
      `${file}: ${action} must state its version in a trailing comment, e.g. \`# v${resolvedMajor}\``
    )
    assert.equal(
      Number(declaredMajorText),
      resolvedMajor,
      `${file}: ${action} comment claims v${declaredMajorText} but the pinned SHA is v${pin.version}`
    )
  }

  // Check each checkout step individually rather than counting markers across
  // the whole file. A count is satisfiable by one comment anywhere in the
  // workflow, which left `GITHUB_TOKEN` readable from `.git/config` for every
  // later step while the audit still reported a pass.
  // Match `uses:` anywhere at step indentation, not only as the first key. A
  // step written as `- name: …` followed by `uses:` on the next line is the
  // common form (this repository uses it in sync-upstream.yml), and anchoring on
  // `- uses:` made exactly those steps invisible, so a checkout that persists
  // credentials passed the audit.
  const checkoutSteps = [
    ...workflow.matchAll(
      /^[ \t]*(?:-[ \t]+)?uses:[ \t]+actions\/checkout[^\n]*/gm
    ),
  ]
  assert.ok(
    checkoutSteps.length > 0,
    `${file}: expected at least one actions/checkout step`
  )
  for (const step of checkoutSteps) {
    const after = workflow.slice(step.index + step[0].length)
    // The block ends at the next sibling step, i.e. the next line that starts a
    // list item with a key. Matching any `- <key>:` (not just an allowlist) is
    // what stops an empty `with:` from swallowing the rest of the job.
    const nextStep = after.search(/^[ \t]*-[ \t]*[A-Za-z][A-Za-z0-9_-]*:/m)
    const block = nextStep === -1 ? after : after.slice(0, nextStep)

    assert.match(
      block,
      /^[ \t]*with:/m,
      `${file}: every actions/checkout step must have a \`with:\` block`
    )
    // Anchored to a YAML key on its own line so a commented-out or string value
    // cannot pass.
    assert.match(
      block,
      /^[ \t]*persist-credentials:[ \t]*false[ \t]*$/m,
      `${file}: every actions/checkout step must set \`persist-credentials: false\` as a real YAML key`
    )
  }
}

const verifyWorkflow = await readFile(
  path.join(workflowRoot, "verify.yml"),
  "utf8"
)
assert.match(verifyWorkflow, /npm ci --ignore-scripts/)

assert.deepEqual(
  violations,
  [],
  `Source audit violations:\n${violations.join("\n")}`
)
console.log("Source and workflow security audit passed")
